### PR TITLE
Qt5 version

### PR DESCRIPTION
**Pull request by mcristg**
An attempt to keep commonqt up to date with respect to Qt

### CODE REVIEW

**Comment by mcristg** [comment]
Changes in commonqt5 are incompatible with qt4, they must be kept in separate branches.

**Comment by luismbo** [comment]
We have a Qt 5 branch at work that's very similar to this. The main difference seems to be that we were able to improve smokegen so that manual patching of the smoke libraries is not necessary. I'll look into reviewing this PR and merging our efforts.

@stassats once the kinks are ironed out, is there any point in keeping Qt 4 support around? Also, can we fork chrisburel's smokegen and smokeqt repos into the commonqt org to help keeping track of what works with CommonQt?

**Comment by Shinmera** [comment]
@luismbo I have forks of qt and the smoke repos that I use to keep track of the version of the precompiled binaries in qt-libs.

https://github.com/Shinmera/smokegen
https://github.com/Shinmera/smokeqt
https://github.com/Shinmera/libcommonqt
https://github.com/Shinmera/qt4

We could merge things in there, though I'd also be fine with keeping the repos in this org.

**Comment by stassats** [comment]
It shouldn't be a different branch, it should be a different repository.

**Comment by stassats** [comment]
I added commonqt/commonqt5 and invited you all to a team, so you can do whatever.

**Comment by luismbo** [comment]
@stassats ok, should we rename the qt package to qt5 then?

**Comment by stassats** [comment]
Not sure about that, I doubt anyone will load them both at the same time.

**Comment by stassats** [comment]
And keeping it the same will simplify porting to the new version.

**Comment by luismbo** [comment]
Ah, right, agreed, but different system names then? Otherwise, I don't see
the point of using different repos.

**Comment by stassats** [comment]
Sure, different system names, different repositories. The current qt4 should still be working and available.

**Comment by luismbo** [comment]
ACK. Closing this and moving on to the new repo.

**Comment by phoe** [comment]
Can't see anything on the new repo yet; I assume it's just been empty so far.

**Comment by Shinmera** [comment]
Yes, I'm sure luis is busy with other things.

**Comment by luismbo** [comment]
Yes, sorry, I'll get to it! We're ironing out some kinks with WebEngine, some issues with exceptions on SBCL/win32, some very weird interactions between Emacs and Qt, etc.

**Comment by phoe** [comment]
No worries, and thanks for your work so far!

**Comment by stassats** [comment]
And it's up to Qt 6 now, can we skip Qt 5 then?

**Comment by phoe** [comment]
Note that https://www.qt.io/blog/add-on-support-in-qt-6.0-and-beyond lists some things that will be available only in Qt 6.2 and are not available now:

     Qt Bluetooth
     Qt Data Visualization
     Qt Lottie Animation
     Qt Multimedia
     Qt NFC
     Qt Positioning
     Qt Quick Dialogs: Folder, Message Box
     Qt Remote Objects
     Qt Sensors
     Qt SerialBus
     Qt SerialPort
     Qt WebChannel
     Qt WebEngine
     Qt WebSockets
     Qt WebView

Do we care about not being able to wrap any of them until then? (I'd list possibly Multimedia and WebView, but these are just wild guesses.)

**Comment by luismbo** [comment]
> And it's up to Qt 6 now, can we skip Qt 5 then?

We have a couple of Qt 5 based versions in production so we'll probably care about it for a while.




> Note that https://www.qt.io/blog/add-on-support-in-qt-6.0-and-beyond lists some things that will be available only in Qt 6.2 and are not available now:
> ...
> Do we care about not being able to wrap any of them until then? (I'd list possibly Multimedia and WebView, but these are just wild guesses.)

WebView/WebEngine is definitely important these days.

**Comment by phoe** [comment]
Yes, to me that's two big reasons for not skipping Qt5 then.

**Comment by vindarel** [comment]
Hi there Lisp hackers, 

do you think you'll have results to share this year, like before Christmas?

Best,

**Comment by luismbo** [comment]
https://github.com/commonqt/commonqt5/ lives. Sorry for taking so long.

**Comment by hakonhagland** [comment]
@mcristg I am not able to submit issues at https://github.com/mcristg/smokegen so apologies for contacting you here. If you have time, could you please take a look at https://github.com/commonqt/commonqt5/issues/4 ?

**Pull request closed without merging**
